version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db

  express:
    build: .
    ports:
      - "4000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://0.0.0.0:27017/telegram_bot_db

volumes:
  mongodb_data:
